# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"

members = [
    "packages/*",
]

[workspace.package]
version = "0.1.0"
authors = ["Nic McPhee", "Many cool people on Twitch"]
description = "An evolutionary computation system in Rust"
documentation = "https://github.com/NicMcPhee/rust-ga"
edition = "2021"

[profile.release]
debug = true

[workspace.dependencies]
anyhow = "1.0.71"
clap = "4.3.11"
rand = "0.8.5"
num-traits = "0.2.15"
thiserror = "1.0.44"
itertools = "0.11.0"

ec-core = { path = "packages/ec-core" }
ec-linear = { path = "packages/ec-linear" }
push = { path = "packages/push" }
