# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"

members = ["packages/*"]
exclude = ["packages/rust-lexicase"]

[workspace.package]
version = "0.1.0"
authors = ["Nic McPhee", "Many cool people on Twitch"]
description = "An evolutionary computation system in Rust"
documentation = "https://github.com/NicMcPhee/rust-ga"
edition = "2021"

[profile.release]
debug = true

[workspace.dependencies]
anyhow = "1.0.79"
clap = "4.4.18"
rand = "0.8.5"
num-traits = "0.2.17"
thiserror = "1.0.56"
itertools = "0.12.1"
macro_railroad_annotation = "1.0.3"

ec-core = { path = "packages/ec-core" }
ec-linear = { path = "packages/ec-linear" }
push = { path = "packages/push" }
push_macros = { path = "packages/push-macros" }


[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"
expect_used = "warn"
module_name_repetitions = "allow"
as_conversions = "deny"


[[workspace.metadata.example_runner.default]]
template = "balanced"

[[workspace.metadata.example_runner.default]]
template = "big_population"

[[workspace.metadata.example_runner.default]]
template = "many_generations"

[workspace.metadata.example_runner.templates.balanced]
type = "ignore"
arguments = [
  "--num-generations",
  "10",
  "--population-size",
  "200"
]

[workspace.metadata.example_runner.templates.big_population]
type = "ignore"
arguments = [
  "--num-generations",
  "1",
  "--population-size",
  "2000"
]

[workspace.metadata.example_runner.templates.many_generations]
type = "ignore"
arguments = [
  "--num-generations",
  "200",
  "--population-size",
  "10"
]
