[package]
name = "ec-push-cli"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
rand = { workspace = true, features = ["alloc"] }

ec-core = { workspace = true }
ec-linear = { workspace = true }
push = { workspace = true }

[[bin]]
name = "pushgp"
path = "src/main.rs"
