[package]
name = "push"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true , features = ["alloc"] }
thiserror = { workspace = true }

ec-core = { workspace = true }
ec-linear = { workspace = true }

proptest = "1.2.0"
strum = "0.25.0"
strum_macros = "0.25.1"
embed-doc-image = "0.1.4"
push_macros = { workspace = true, optional = true }
collectable = "0.0.2"
ordered-float = "4.1.1"

[dev-dependencies]
clap = { version = "4.3.11", features = ["derive"] }

[features]
default = ["macros"]
macros = ["dep:push_macros"]
