[package]
name = "push"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
num-traits = "0.2.15"
rand = { version = "0.8.5", features = ["alloc"] }

ec-core = { path = "../ec-core" }
ec-linear = { path = "../ec-linear" }
