[package]
name = "push"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true , features = ["alloc"] }
thiserror = { workspace = true }

ec-core = { workspace = true }
ec-linear = { workspace = true }

proptest = "1.2.0"
strum = "0.25.0"
strum_macros = "0.25.1"
