[package]
name = "rust-lexicase"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_lexicase"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.1", features = ["anyhow"] }
ec-core = { path = "../ec-core" }
numpy = "0.19.0"
rand = { workspace = true }

[lints]
workspace = true

